// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiZt_JgE4v0ltEIsvAeNwIS0veiQ12q9c',
    appId: '1:775401130552:web:ef4cf75ac586ab3c6bb4cd',
    messagingSenderId: '775401130552',
    projectId: 'gamer-galaxy-d6e09',
    authDomain: 'gamer-galaxy-d6e09.firebaseapp.com',
    storageBucket: 'gamer-galaxy-d6e09.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAreR-TGmfmYN7kqasM_kkmxdDNgPUbj2o',
    appId: '1:775401130552:android:012b3cda287394cc6bb4cd',
    messagingSenderId: '775401130552',
    projectId: 'gamer-galaxy-d6e09',
    storageBucket: 'gamer-galaxy-d6e09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfoSXWUCdqqeC9CDKjblhutgmUqFOYmn8',
    appId: '1:775401130552:ios:98e898ede0decd426bb4cd',
    messagingSenderId: '775401130552',
    projectId: 'gamer-galaxy-d6e09',
    storageBucket: 'gamer-galaxy-d6e09.appspot.com',
    iosClientId: '775401130552-msgr01v2qjecm213mvs6f7ualbsl1cg2.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyecto902',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfoSXWUCdqqeC9CDKjblhutgmUqFOYmn8',
    appId: '1:775401130552:ios:98e898ede0decd426bb4cd',
    messagingSenderId: '775401130552',
    projectId: 'gamer-galaxy-d6e09',
    storageBucket: 'gamer-galaxy-d6e09.appspot.com',
    iosClientId: '775401130552-msgr01v2qjecm213mvs6f7ualbsl1cg2.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyecto902',
  );
}
